# .github/workflows/playwright.yml
name: Playwright Tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  actions: write

on:
  push:
    branches: [dev]
  pull_request:
    branches: [master]

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'

      - name: Set up Docker Buildx
        if: github.ref == 'refs/heads/dev'
        uses: docker/setup-buildx-action@v3

      - name: Build Docker dev image
        if: github.ref == 'refs/heads/dev'
        run: docker build -f Dockerfile.dev -t talent-calculator:dev .

      - name: Start app container
        if: github.ref == 'refs/heads/dev'
        run: |
          docker run -d --name talent-app -p 5173:5173 talent-calculator:dev
          echo "APP_URL=http://localhost:5173" >> $GITHUB_ENV

      - name: Wait for app to be ready
        if: github.ref == 'refs/heads/dev'
        run: npx wait-on $APP_URL

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test

      - name: Stop app container
        if: always() && github.ref == 'refs/heads/dev'
        run: docker stop talent-app

      - name: Upload Playwright HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/

      - name: Upload JUnit Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-results
          path: test-results/**/*.xml

      - name: Upload Failure Screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: failure-screenshots
          path: test-results/screenshots/

      - name: Upload Failure Videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: failure-videos
          path: test-results/videos/