# .github/workflows/units.yml

name: Unit Tests

permissions:
  contents: read

on:
  push:
    branches: [dev, master]
  pull_request:
    branches: [dev, master]

jobs:
  run_unit_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint and Prettier checks
        run: npm run lint

      - name: Run TypeScript check
        run: npm run check

      - name: Run unit tests
        run: npm run test:unit